# Trabajo práctico 1: Sistemas lineales

Importando PyTorch

In [43]:
import torch

Definiendo función para comparar salidas

In [44]:
def compare_outputs(u, v):
    if torch.equal(u, v):
        print("Las salidas son iguales, se cumple la superposicion y la homogeneidad")
    else:
        print("Las salidas no son iguales, no se cumple la superposicion y la homogeneidad")

## Ejercicio 1

### Demuestre si los siguientes sistemas L{ } (con entrada u(t) y salida g(t), y h(t) una función cualquiera) son lineales o no lineales

Creando una entrada un arreglo de 50 valores generados al azar y definiendo ${\alpha}$ y ${\beta}$

In [45]:
u1 = torch.rand(50)
u2 = torch.rand(50)
alpha = torch.rand(1)
beta = torch.rand(1)

print(f"Entrada u1(t): \n{u1}")
print(f"Entrada u2(t): \n{u2}")
print(f"alpha: {alpha}")
print(f"beta: {beta}")

Entrada u1(t): 
tensor([1.7250e-02, 2.0554e-01, 7.6865e-01, 5.1915e-01, 5.6444e-01, 2.7322e-01,
        7.3498e-01, 3.1526e-01, 2.5351e-01, 5.6290e-01, 6.5619e-01, 9.7857e-01,
        1.1664e-01, 5.3775e-01, 5.4148e-01, 3.0490e-01, 6.8357e-01, 9.0861e-02,
        5.3830e-01, 5.3050e-02, 3.1605e-02, 4.2575e-01, 9.5412e-01, 5.8261e-01,
        6.6186e-03, 7.4192e-02, 4.7563e-02, 9.8122e-01, 8.3172e-01, 6.9436e-02,
        2.8646e-01, 5.4085e-01, 2.9304e-01, 1.3604e-01, 4.5421e-02, 6.0402e-01,
        7.0834e-01, 4.6197e-01, 8.5131e-01, 3.2151e-01, 3.7235e-01, 8.3028e-01,
        9.3222e-05, 6.2536e-01, 9.7852e-01, 3.3787e-01, 1.4159e-01, 3.8720e-01,
        6.3112e-01, 4.9993e-01])
Entrada u2(t): 
tensor([0.4644, 0.2851, 0.3460, 0.6736, 0.1547, 0.5698, 0.9033, 0.7651, 0.2249,
        0.0135, 0.3296, 0.9960, 0.7518, 0.6658, 0.6230, 0.8488, 0.7097, 0.9144,
        0.3499, 0.6573, 0.9742, 0.8068, 0.7193, 0.2327, 0.4960, 0.2429, 0.1833,
        0.0765, 0.0247, 0.6640, 0.8936, 0.2322, 0.7353,



1.   g(t) = u(t) + 3

Usando como entrada ${\alpha}$${u_{1}(t)}$ + ${\beta}$${u_{2}(t)}$ se tiene:

${L\{{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}\}}$ = ${\alpha}$${u_{1}(t)}$ + ${\beta}$${u_{2}(t)}$ + 3

Para que el sistema sea lineal la salida debe ser:

${L\{g(t)\}}$ = ${{\alpha}L\{u_{1}(t)\}}$ + ${{\beta}L\{u_{2}(t)\}}$ = ${\alpha}$(${u_{1}(t)}$ + 3) + ${\beta}$(${u_{2}(t)}$ + 3)

Computando ambos casos:

In [46]:
L_input = alpha*u1 + (beta*u2) + 3
print(f"alpha*u1 + beta*u2 + 3: \n{L_input}\n")

L_linear = alpha*u1 + beta*u2 + 6
print(f"alpha*u1 + beta*u2 + 6: \n{L_linear}\n")

compare_outputs(L_input, L_linear)

alpha*u1 + beta*u2 + 3: 
tensor([3.2548, 3.2741, 3.6458, 3.6678, 3.4219, 3.4647, 3.9188, 3.5929, 3.2713,
        3.3467, 3.5693, 4.1146, 3.4661, 3.6748, 3.6546, 3.6307, 3.7859, 3.5361,
        3.5089, 3.3780, 3.5319, 3.6815, 3.9542, 3.4739, 3.2651, 3.1726, 3.1252,
        3.6322, 3.5147, 3.3914, 3.6432, 3.4485, 3.5638, 3.1573, 3.1598, 3.5616,
        3.8959, 3.6349, 3.5568, 3.3039, 3.7330, 3.7631, 3.0611, 3.5825, 3.9968,
        3.4964, 3.3487, 3.4541, 3.7362, 3.5148])

alpha*u1 + beta*u2 + 6: 
tensor([6.2548, 6.2741, 6.6458, 6.6678, 6.4219, 6.4647, 6.9188, 6.5929, 6.2713,
        6.3467, 6.5693, 7.1146, 6.4661, 6.6748, 6.6546, 6.6307, 6.7859, 6.5361,
        6.5089, 6.3780, 6.5319, 6.6815, 6.9542, 6.4739, 6.2651, 6.1726, 6.1252,
        6.6322, 6.5147, 6.3914, 6.6432, 6.4485, 6.5638, 6.1573, 6.1598, 6.5616,
        6.8959, 6.6349, 6.5568, 6.3039, 6.7330, 6.7631, 6.0611, 6.5825, 6.9968,
        6.4964, 6.3487, 6.4541, 6.7362, 6.5148])

Las salidas no son iguales, no se cumple la superp


2.   g(t) = u(t)h(t)

Usando como entrada ${\alpha}$${u_{1}(t)}$ + ${\beta}$${u_{2}(t)}$ se tiene:

${L\{{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}\}}$ = ${\alpha}$${u_{1}(t)}$h(t) + ${\beta}$${u_{2}(t)}$h(t)

Para que el sistema sea lineal la salida debe ser:

${L\{g(t)\}}$ = ${{\alpha}L\{u_{1}(t)\}}$ + ${{\beta}L\{u_{2}(t)\}}$ = ${\alpha}$${u_{1}(t)}$h(t) + ${\beta}$${u_{2}(t)}$h(t)

y h(t) es constante e independiente de u(t)

Computando ambos casos:

In [47]:
# Creando una funcion h cualquiera
h = torch.rand(50)

L_input = (alpha*u1*h) + (beta*u2*h)
print(f"(alpha*u*h) + (beta*u*h): \n{L_input}\n")

L_linear = (alpha*u1*h) + (beta*u2*h)
print(f"(alpha*u*h) + (beta*u*h): \n{L_linear}\n")

compare_outputs(L_input, L_linear)

(alpha*u*h) + (beta*u*h): 
tensor([0.1617, 0.0710, 0.6067, 0.4222, 0.2157, 0.1256, 0.6885, 0.1512, 0.0849,
        0.3092, 0.5533, 0.8334, 0.0011, 0.1299, 0.0201, 0.0185, 0.1988, 0.1935,
        0.0797, 0.1365, 0.2358, 0.3095, 0.2589, 0.1714, 0.1003, 0.1715, 0.1045,
        0.3174, 0.0062, 0.0183, 0.2508, 0.1989, 0.4470, 0.0207, 0.1568, 0.3312,
        0.7280, 0.1373, 0.5565, 0.2360, 0.0324, 0.6426, 0.0359, 0.0571, 0.3599,
        0.0393, 0.3348, 0.4353, 0.1020, 0.1689])

(alpha*u*h) + (beta*u*h): 
tensor([0.1617, 0.0710, 0.6067, 0.4222, 0.2157, 0.1256, 0.6885, 0.1512, 0.0849,
        0.3092, 0.5533, 0.8334, 0.0011, 0.1299, 0.0201, 0.0185, 0.1988, 0.1935,
        0.0797, 0.1365, 0.2358, 0.3095, 0.2589, 0.1714, 0.1003, 0.1715, 0.1045,
        0.3174, 0.0062, 0.0183, 0.2508, 0.1989, 0.4470, 0.0207, 0.1568, 0.3312,
        0.7280, 0.1373, 0.5565, 0.2360, 0.0324, 0.6426, 0.0359, 0.0571, 0.3599,
        0.0393, 0.3348, 0.4353, 0.1020, 0.1689])

Las salidas son iguales, se cumple la superpos


3.   g(t) = max(u(t))

Usando como entrada ${\alpha}$${u_{1}(t)}$ + ${\beta}$${u_{2}(t)}$ se tiene:

${L\{{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}\}}$ = max(${{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}}$)


Para que el sistema sea lineal la salida debe ser:

${L\{g(t)\}}$ = ${{\alpha}L\{u_{1}(t)\}}$ + ${{\beta}L\{u_{2}(t)\}}$ = ${\alpha}$max(${u_{1}(t)}$) + ${\beta}$max(${u_{2}(t)}$)

Computando ambos casos:

In [48]:
L_input = torch.max(alpha*u1 + beta*u2)
print(f"max(alpha*u1 + beta*u2): \n{L_input}\n")

L_linear = alpha*torch.max(u1) + beta*torch.max(u2)
print(f"alpha*torch.max(u1) + beta*torch.max(u2): \n{L_linear}\n")

compare_outputs(L_input, L_linear)

max(alpha*u1 + beta*u2): 
1.1145769357681274

alpha*torch.max(u1) + beta*torch.max(u2): 
tensor([1.1162])

Las salidas no son iguales, no se cumple la superposicion y la homogeneidad



4.   g(t) = |u(t)|

Usando como entrada ${\alpha}$${u_{1}(t)}$ + ${\beta}$${u_{2}(t)}$ se tiene:

${L\{{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}\}}$ = |${{\alpha}{u_{1}(t)} + {\beta}{u_{2}(t)}}$|

Para que el sistema sea lineal la salida debe ser:

${L\{g(t)\}}$ = ${\alpha}$|${u_{1}(t)}$| + ${\beta}$|${u_{2}(t)}$|

Computando ambos casos:

In [49]:
L_input = torch.abs(alpha*u1 + beta*u2)
print(f"|alpha*u1 + beta*u2|: \n{L_input}\n")

L_linear = alpha*torch.abs(u1) + beta*torch.abs(u2)
print(f"alpha*torch.max(u1) + beta*torch.max(u2): \n{L_linear}\n")

compare_outputs(L_input, L_linear)

|alpha*u1 + beta*u2|: 
tensor([0.2548, 0.2741, 0.6458, 0.6678, 0.4219, 0.4647, 0.9188, 0.5929, 0.2713,
        0.3467, 0.5693, 1.1146, 0.4661, 0.6748, 0.6546, 0.6307, 0.7859, 0.5361,
        0.5089, 0.3780, 0.5319, 0.6815, 0.9542, 0.4739, 0.2651, 0.1726, 0.1252,
        0.6322, 0.5147, 0.3914, 0.6432, 0.4485, 0.5638, 0.1573, 0.1598, 0.5616,
        0.8959, 0.6349, 0.5568, 0.3039, 0.7330, 0.7631, 0.0611, 0.5825, 0.9968,
        0.4964, 0.3487, 0.4541, 0.7362, 0.5148])

alpha*torch.max(u1) + beta*torch.max(u2): 
tensor([0.2548, 0.2741, 0.6458, 0.6678, 0.4219, 0.4647, 0.9188, 0.5929, 0.2713,
        0.3467, 0.5693, 1.1146, 0.4661, 0.6748, 0.6546, 0.6307, 0.7859, 0.5361,
        0.5089, 0.3780, 0.5319, 0.6815, 0.9542, 0.4739, 0.2651, 0.1726, 0.1252,
        0.6322, 0.5147, 0.3914, 0.6432, 0.4485, 0.5638, 0.1573, 0.1598, 0.5616,
        0.8959, 0.6349, 0.5568, 0.3039, 0.7330, 0.7631, 0.0611, 0.5825, 0.9968,
        0.4964, 0.3487, 0.4541, 0.7362, 0.5148])

Las salidas son iguales, se cumple

## Ejercicio 2

### Demuestre si los siguientes sistemas con múltiples variables de entrada L{ } (con entrada vectorial \vec{u} y salida escalar s ϵ ${\mathbb{R}}$ cumplen homogeneidad y superposición

Creando 50 vectores de dimesión (1x5) al azar de dimensionalidad y definiendo ${\alpha}$ y ${\beta}$



In [50]:
u1 = torch.rand(50, 5)
u2 = torch.rand(50, 5)
alpha = torch.rand(1)
beta = torch.rand(1)

print(f"Entradas u1(t): \n{u1}")
print(f"Entradas u2(t): \n{u2}")
print(f"alpha: {alpha}")
print(f"beta: {beta}")

Entradas u1(t): 
tensor([[0.4000, 0.6810, 0.0532, 0.7226, 0.5156],
        [0.2346, 0.9395, 0.8701, 0.2825, 0.2733],
        [0.2478, 0.0458, 0.7411, 0.6674, 0.8444],
        [0.4803, 0.9300, 0.5280, 0.5577, 0.2295],
        [0.0400, 0.7318, 0.8202, 0.9026, 0.9671],
        [0.4675, 0.5287, 0.0111, 0.3143, 0.5616],
        [0.9390, 0.1620, 0.8239, 0.1707, 0.5304],
        [0.3491, 0.0747, 0.6539, 0.2629, 0.6196],
        [0.1213, 0.2473, 0.0585, 0.4831, 0.6223],
        [0.2722, 0.9604, 0.5929, 0.9283, 0.7530],
        [0.0083, 0.1466, 0.8658, 0.3824, 0.3289],
        [0.8167, 0.4923, 0.1574, 0.0308, 0.2937],
        [0.9888, 0.5301, 0.7602, 0.9958, 0.7252],
        [0.4675, 0.9371, 0.1171, 0.5565, 0.5322],
        [0.7294, 0.3657, 0.0893, 0.5135, 0.0035],
        [0.6132, 0.3578, 0.4581, 0.0406, 0.6836],
        [0.5426, 0.3022, 0.8966, 0.4523, 0.0243],
        [0.3260, 0.6571, 0.0902, 0.0731, 0.6889],
        [0.2120, 0.1080, 0.1066, 0.2034, 0.1679],
        [0.0706, 0.2118, 0.5444, 



1.   Norma de Manhattan ${\ell_{1}}$

Usando como entrada ${\vec{u}}$ = ${\alpha}$${\vec{u}_{1}}$ + ${\beta}$${\vec{u}_{2}}$ se tiene:

${||\vec{u}||_{1}}$ = ${\sum_{i=1}^{n}|\alpha u_{1i} + \beta u_{2i}|}$

Para que el sistema sea lineal la salida debe ser:

${||\vec{u}||_{1}}$ = ${|\alpha|}$${\sum_{i=1}^{n}|\vec{u}_{1i}|}$ + ${|\beta|}$${\sum_{i=1}^{n}|\vec{u}_{2i}|}$

Computando ambos casos:

In [51]:
L_input = torch.norm(alpha*u1 + beta*u2, p=1, dim=1)

print(f"||alpha*u1 + beta*u2||_1: \n{L_input}\n")

L_linear = torch.abs(alpha)*torch.sum(torch.abs(u1), dim=1) + torch.abs(beta)*torch.sum(torch.abs(u2), dim=1)
print(f"||alpha*u1 + beta*u2||_1: \n{L_linear}\n")

compare_outputs(L_input, L_linear)

||alpha*u1 + beta*u2||_1: 
tensor([2.8239, 3.1191, 3.1126, 3.2423, 3.3812, 2.4512, 3.0129, 2.9445, 2.3415,
        3.8467, 2.3436, 2.0919, 4.1993, 3.2036, 2.7177, 2.8478, 2.4309, 2.1991,
        1.8826, 2.5233, 2.6283, 2.7314, 2.8921, 2.4113, 2.9845, 2.4020, 3.8626,
        3.4706, 2.6022, 2.7909, 3.3375, 2.3990, 3.4370, 2.6011, 3.3668, 3.1606,
        2.8067, 1.8854, 3.1873, 2.6061, 2.4826, 3.8282, 2.2648, 2.5426, 2.2667,
        3.4035, 2.6994, 4.4334, 3.3580, 1.7180])

||alpha*u1 + beta*u2||_1: 
tensor([2.8239, 3.1191, 3.1126, 3.2423, 3.3812, 2.4512, 3.0129, 2.9445, 2.3415,
        3.8467, 2.3436, 2.0919, 4.1993, 3.2036, 2.7177, 2.8478, 2.4309, 2.1991,
        1.8826, 2.5233, 2.6283, 2.7314, 2.8921, 2.4113, 2.9845, 2.4020, 3.8626,
        3.4706, 2.6022, 2.7909, 3.3375, 2.3990, 3.4370, 2.6011, 3.3668, 3.1606,
        2.8067, 1.8854, 3.1873, 2.6061, 2.4826, 3.8282, 2.2648, 2.5426, 2.2667,
        3.4035, 2.6994, 4.4334, 3.3580, 1.7180])

Las salidas no son iguales, no se cumple la su


2.   Norma Euclidiana ${\ell_{2}}$

Usando como entrada ${\vec{u}}$ = ${\alpha}$${\vec{u}_{1}}$ + ${\beta}$${\vec{u}_{2}}$ se tiene:

${||\vec{u}||_{2}}$ = ${\sqrt{ \sum_{i=1}^{n} (\alpha u_{1i} + \beta u_{2i})^{2} }}$

Para que el sistema sea lineal la salida debe ser:

${||\vec{u}||_{2}}$ = ${|\alpha|}$${\sqrt{ \sum_{i=1}^{n} (u_{1i})^{2} }}$ + ${\beta}$${\sqrt{ \sum_{i=1}^{n} (u_{2i})^{2} }}$

Computando ambos casos:

In [52]:
L_input = torch.norm(alpha*u1 + beta*u2, p=2, dim=1)

print(f"||alpha*u1 + beta*u2||_2: \n{L_input}\n")

L_linear = torch.abs(alpha)*torch.sqrt(torch.sum(torch.pow(u1, 2), dim=1)) + torch.abs(beta)*torch.sqrt(torch.sum(torch.pow(u2, 2), dim=1))
print(f"||alpha*u1 + beta*u2||_2: \n{L_linear}\n")

compare_outputs(L_input, L_linear)

||alpha*u1 + beta*u2||_2: 
tensor([1.3496, 1.5351, 1.5531, 1.5185, 1.6400, 1.1507, 1.4758, 1.3870, 1.1598,
        1.8063, 1.1397, 1.1356, 1.9199, 1.4709, 1.3326, 1.3104, 1.2196, 1.1588,
        0.8485, 1.2379, 1.2262, 1.2837, 1.5000, 1.1739, 1.4552, 1.1030, 1.7908,
        1.7406, 1.1947, 1.3333, 1.5364, 1.1347, 1.6033, 1.2917, 1.5996, 1.4328,
        1.3542, 0.8749, 1.4844, 1.2189, 1.3337, 1.8444, 1.1713, 1.2409, 1.1371,
        1.5472, 1.2933, 2.0004, 1.5714, 0.8323])

||alpha*u1 + beta*u2||_2: 
tensor([1.3850, 1.6154, 1.6085, 1.5438, 1.6728, 1.2632, 1.5574, 1.4492, 1.2146,
        1.8737, 1.2694, 1.1685, 2.0077, 1.6176, 1.4013, 1.3897, 1.3296, 1.2414,
        0.8795, 1.3454, 1.3655, 1.3558, 1.5343, 1.2816, 1.5105, 1.3346, 1.8454,
        1.7565, 1.4405, 1.4562, 1.6038, 1.3597, 1.6863, 1.5428, 1.7022, 1.4883,
        1.3631, 0.9127, 1.5446, 1.2930, 1.4544, 1.9279, 1.2371, 1.3586, 1.2551,
        1.5653, 1.4167, 2.0699, 1.5994, 0.8903])

Las salidas no son iguales, no se cumple la su



3.   Norma ${\ell_{\infty}}$

Usando como entrada ${\vec{u}}$ = ${\alpha}$${\vec{u}_{1}}$ + ${\beta}$${\vec{u}_{2}}$ se tiene:

${||\vec{u}||_{\infty}}$ $\approx$ ${max(|\alpha u_{1i} + \beta u_{2i}|)}$

Para que el sistema sea lineal la salida debe ser:

${||\vec{u}||_{\infty}}$ $\approx$ ${|\alpha|}$max(${u_{1i}}$) + ${|\beta|}$max(${u_{2i}}$)

Computando ambos casos:

In [53]:
L_input = torch.norm(alpha*u1 + beta*u2, p=torch.inf, dim=1)

print(f"||alpha*u1 + beta*u2||_inf: \n{L_input}\n")

L_linear = torch.abs(alpha) * torch.max(torch.abs(u1), dim=1)[0] + torch.abs(beta) * torch.max(torch.abs(u2), dim=1)[0]
print(f"||alpha*u1 + beta*u2||_inf: \n{L_linear}\n")

compare_outputs(L_input, L_linear)

||alpha*u1 + beta*u2||_inf: 
tensor([0.7947, 1.1085, 1.0534, 0.9662, 0.9168, 0.7332, 0.9792, 0.8596, 0.7368,
        1.1374, 0.8563, 0.8702, 1.0953, 0.8047, 0.8913, 0.7537, 0.7695, 0.8764,
        0.4567, 0.9188, 0.7483, 0.7333, 1.1474, 0.8163, 0.8688, 0.6074, 0.9541,
        1.1167, 0.7203, 0.8841, 0.9167, 0.7714, 0.9923, 0.8394, 1.0184, 0.7447,
        0.8711, 0.5524, 0.9940, 0.8148, 0.9606, 0.9872, 0.8075, 0.9100, 0.7681,
        0.8316, 0.7827, 1.0539, 0.9671, 0.5261])

||alpha*u1 + beta*u2||_inf: 
tensor([0.8280, 1.1085, 1.0534, 1.0399, 0.9683, 0.8084, 1.0832, 0.9177, 0.8419,
        1.1631, 0.9699, 0.8702, 1.1945, 1.1146, 0.9311, 0.8604, 1.0528, 0.9019,
        0.5411, 1.0028, 1.0541, 0.8643, 1.1474, 0.9530, 0.9342, 0.9689, 0.9670,
        1.1589, 1.0564, 1.1011, 1.0142, 1.0172, 1.0748, 1.1139, 1.1187, 0.8654,
        0.8711, 0.5918, 0.9987, 0.8148, 1.1202, 1.1778, 1.0129, 1.1081, 0.9001,
        0.9606, 0.9562, 1.1515, 1.0007, 0.6555])

Las salidas no son iguales, no se cumple l